import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Analytics } from "@vercel/analytics/next"

import { Toaster } from 'react-hot-toast'
import { TRPCReactProvider } from "@/trpc/client";

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} antialiased`}
      >
        <TRPCReactProvider>
          <Toaster />
          {children}
          <Analytics />
        </TRPCReactProvider>
      </body>
    </html>
  );
}
