export const businessSubcategories: Array<{ value: string; label: string }> = [
    { value: "agriculture", label: "Agriculture Supplies" },
    { value: "books", label: "Books & Literature" },
    { value: "electronics_and_furniture", label: "Electronics & Furniture" },
    { value: "fashion_and_lifestyle", label: "Fashion & Lifestyle" },
    { value: "gifting", label: "Gifts & Hampers" },
    { value: "grocery", label: "Grocery & Daily Essentials" },
    { value: "baby_products", label: "Baby Products" },
    { value: "office_supplies", label: "Office Supplies" },
    { value: "religious_products", label: "Religious Items" },
    { value: "pet_products", label: "Pet Supplies" },
    { value: "sports_products", label: "Sports & Fitness Gear" },
    { value: "arts_and_collectibles", label: "Arts & Collectibles" },
    { value: "sexual_wellness_products", label: "Sexual Wellness" },
    { value: "drop_shipping", label: "Dropshipping Store" },
    { value: "crypto_machinery", label: "Crypto Mining Equipment" },
    { value: "tobacco", label: "Tobacco Products" },
    { value: "weapons_and_ammunitions", label: "Weapons & Ammunition" },
    { value: "stamps_and_coin_stores", label: "Stamps & Coins" },
    { value: "automobile_parts_and_equipments", label: "Auto Parts & Accessories" },
    { value: "garden_supply_stores", label: "Garden & Outdoor Supplies" },
    { value: "household_appliance_stores", label: "Home Appliances" },
    { value: "non_durable_goods", label: "Non-Durable Consumer Goods" },
    { value: "pawn_shops", label: "Pawn & Thrift Stores" },
    { value: "wig_and_toupee_shops", label: "Wigs & Hair Accessories" },
    { value: "camera_and_photographic_stores", label: "Camera & Photography" },
    { value: "leather_goods_and_luggage", label: "Leather Goods & Bags" },
    { value: "men_and_boys_clothing_stores", label: "Men’s & Boys’ Clothing" },
    { value: "tent_stores", label: "Tents & Outdoor Gear" },
    { value: "shoe_stores", label: "Footwear & Shoes" },
    { value: "petroleum_and_petroleum_products", label: "Fuel & Petroleum Products" },
    { value: "automotive_tire_stores", label: "Tires & Auto Care" },
    { value: "chemical_and_allied_products", label: "Chemical Supplies" },
    { value: "family_clothing_stores", label: "Family Clothing & Apparel" },
    { value: "fabric_and_sewing_stores", label: "Fabrics & Sewing Supplies" },
    { value: "art_supply_stores", label: "Art Supplies" },
    { value: "clocks_and_silverware_stores", label: "Clocks & Silverware" },
    { value: "cosmetic_stores", label: "Beauty & Cosmetics" },
    { value: "home_furnishing_stores", label: "Home Furnishings" },
    { value: "antique_stores", label: "Antiques & Vintage Items" },
    { value: "women_clothing", label: "Women’s Clothing" },
    { value: "women_accessory_stores", label: "Women’s Accessories" },
]